import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-todo-table',
  templateUrl: './todo-table.component.html',
  styleUrls: ['./todo-table.component.scss']
})
export class TodoTableComponent implements OnInit {
  todoList = [
    {
       "PkPredmetPismenoTask":1,
       "IDPredmetPismenoTask":"TSK-00001\/17",
       "KratkiOpis":"Ovo je probni zadatak za prezentaciju",
       "RokIzvrsenja":"2020-11-15",
       "PkUserTaskNositelj":1,
       "Nositelj":"Admin, Lama",
       "PkTaskStatus":2,
       "IDTaskStatus":"WIP",
       "NazivTaskStatus":"Work in progress",
       "PkTaskVrsta":1,
       "IDTaskVrsta":"TSV-1",
       "NazivTaskVrsta":"Izrada dokumenta",
       "PostotakIzvrsenja":20,
       "DatumUnosa":"2020-11-11T09:08:08.220",
       "PkUseraUnos":1,
       "Promijenio":"Admin, Lama",
       "DatumZadnjePromjene":"2020-11-11T09:08:08.220",
       "RowVersion":"0x000000001B320553",
       "PkUsera":1,
       "Unio":"Admin, Lama",
       "PripadnostZadatka":0
    },
    {
       "PkPredmetPismenoTask":2,
       "IDPredmetPismenoTask":"TSK-00001\/20",
       "KratkiOpis":"Molim te organiziraj prezentaciju i potrebne materijale.",
       "RokIzvrsenja":"2021-07-29",
       "PkUserTaskNositelj":11,
       "Nositelj":"Radmilo, Ivana",
       "PkTaskStatus":1,
       "IDTaskStatus":"NS",
       "NazivTaskStatus":"Not Started",
       "PkTaskVrsta":3,
       "IDTaskVrsta":"TSV-3",
       "NazivTaskVrsta":"Organizacija sastanka",
       "PostotakIzvrsenja":0,
       "DatumUnosa":"2021-07-22T14:11:59.187",
       "PkUseraUnos":1,
       "Promijenio":"Admin, Lama",
       "DatumZadnjePromjene":"2021-07-22T14:11:59.187",
       "RowVersion":"0x000000001B3ECB40",
       "PkUsera":1,
       "Unio":"Admin, Lama",
       "PripadnostZadatka":0
    },
    {
       "PkPredmetPismenoTask":3,
       "IDPredmetPismenoTask":"TSK-00002\/21",
       "KratkiOpis":"Izradi plan rada za 2022 godinu",
       "RokIzvrsenja":"2021-07-31",
       "PkUserTaskNositelj":1,
       "Nositelj":"Admin, Lama",
       "PkTaskStatus":2,
       "IDTaskStatus":"WIP",
       "NazivTaskStatus":"Work in progress",
       "PkTaskVrsta":1,
       "IDTaskVrsta":"TSV-1",
       "NazivTaskVrsta":"Izrada dokumenta",
       "OpisAktivnosti":"1. Kontaktirao voditelje sektora u firmi i prikupio njihove potrebe.\n2.Razgovarao s Upravom i prikupio njihove planove i strateÅ¡ke potrebe u slijedeÄ‡eoj godini\n3. napravio plan investicija u IT opremu\n4. napravio plan zamjene dotrajale It opreme",
       "PostotakIzvrsenja":40,
       "DatumUnosa":"2021-07-22T14:12:45.307",
       "PkUseraUnos":1,
       "Promijenio":"Admin, Lama",
       "DatumZadnjePromjene":"2021-07-22T14:14:33.887",
       "RowVersion":"0x000000001B3ECB44",
       "PkUsera":1,
       "Unio":"Admin, Lama",
       "PripadnostZadatka":0
    },
    {
       "PkPredmetPismenoTask":4,
       "IDPredmetPismenoTask":"423",
       "IDPredmet":"3-1-10001",
       "PkPismeno":1751,
       "UrudzbeniBroj":"01-22-01",
       "KratkiOpis":"fdgdhrd",
       "RokIzvrsenja":"2022-01-31",
       "PkUserTaskNositelj":1,
       "Nositelj":"Admin, Lama",
       "PkTaskStatus":2,
       "IDTaskStatus":"WIP",
       "NazivTaskStatus":"Work in progress",
       "PkTaskVrsta":1,
       "IDTaskVrsta":"TSV-1",
       "NazivTaskVrsta":"Izrada dokumenta",
       "OpisAktivnosti":"grfreg",
       "PostotakIzvrsenja":55,
       "DatumUnosa":"2022-01-31T09:09:56.163",
       "PkUseraUnos":1,
       "Promijenio":"Admin, Lama",
       "DatumZadnjePromjene":"2022-01-31T09:09:56.163",
       "RowVersion":"0x000000001B40E167",
       "PkUsera":1,
       "Unio":"Admin, Lama",
       "zadatakPismena":1751,
       "PripadnostZadatka":1
    },
    {
       "PkPredmetPismenoTask":5,
       "IDPredmetPismenoTask":"TSK-00001\/21",
       "IDPredmet":"1-1-02007",
       "PkPismeno":1780,
       "UrudzbeniBroj":"01-22-81",
       "BrojDokumenta":"15249\/43\/1",
       "KratkiOpis":"MOlim te kontaktiraj",
       "RokIzvrsenja":"2022-03-17",
       "PkUserTaskNositelj":5,
       "Nositelj":"DraÅ¡koviÄ‡, Damir",
       "PkTaskStatus":2,
       "IDTaskStatus":"WIP",
       "NazivTaskStatus":"Work in progress",
       "PkTaskVrsta":2,
       "IDTaskVrsta":"TSV-2",
       "NazivTaskVrsta":"Kontakt stranke",
       "PostotakIzvrsenja":55,
       "DatumUnosa":"2022-03-17T09:27:37.757",
       "PkUseraUnos":1,
       "Promijenio":"Admin, Lama",
       "DatumZadnjePromjene":"2022-03-17T09:27:55.233",
       "RowVersion":"0x000000001B411D4F",
       "PkUsera":1,
       "Unio":"Admin, Lama",
       "zadatakPismena":1780,
       "PripadnostZadatka":1
    }
 ]

  constructor() { }

  ngOnInit(): void {
  }

}
